default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['PG_USERNAME'] || 'your_username' %> # Set the Postgres username
  password: <%= ENV['PG_PASSWORD'] || 'your_password' %> # Set the Postgres password
  host: <%= ENV['PG_HOST'] || 'localhost' %> # Set your Postgres host

development:
  <<: *default
  database: kliperr_development

test:
  <<: *default
  database: kliperr_test

production:
  <<: *default
  database: kliperr_production
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  host: <%= ENV['PG_HOST'] %>